
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import TosterContext from "./context/ToasterContext";
import AuthContextProvider from "./context/AuthContext";

import "./globals.css";
const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Messanger project",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <AuthContextProvider>
          <TosterContext />
          {children}
        </AuthContextProvider>
      </body>
    </html>
  );
}
